<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <RootNamespace>Brx.Text</RootNamespace>
      <AssemblyName>Brx.Text</AssemblyName>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
